train:
    seed: 2
    batch_size: 2048
    n_epochs: 20000
    val_interval: 50
    num_workers: 25
    drop_last: false
    base_path: 'data/sleep-edfx'
    output_dir: '/project/output_VAE'
    run_dir: 'aekl_eeg'
    experiment: 'AEKL'
models:
  optimizer_g_lr: 0.005 #Mexer, menor 10E-4
  optimizer_d_lr: 0.0005 #Maior que o anterior 
  adv_weight: 0.01  #
  kl_weight: 1E-9   #
  spectral_weight: 1E4 # testando 1e4, era 1e6

autoencoderkl:
  params:
    spatial_dims: 1 
    in_channels: 62
    out_channels: 62
    num_res_blocks: 2
    norm_num_groups: 1 # talvez colocar 16, 32 
    attention_levels: [false, false, false]
    with_encoder_nonlocal_attn: false
    with_decoder_nonlocal_attn: false

patchdiscriminator:
  params:
    spatial_dims: 1
    num_layers_d: 3
    num_channels: 62
    in_channels: 62
    out_channels: 62
    kernel_size: 3
    norm: "BATCH"
    bias: false
    padding: 1

unet:
  params:
    image_size: 750
    in_channels: 1
    out_channels: 1
    model_channels: 64
    attention_resolutions: [8,4]
    num_res_blocks: 2
    channel_mult: [1,2]
    dropout: 0.0
    conv_resample: True
    num_heads: 1
    use_scale_shift_norm: False
    resblock_updown: True

#latent_channels: 1 # Talvez trocar para 3


train_ldm:
    seed: 2
    batch_size: 1024
    n_epochs: 5000
    eval_freq: 50
    num_workers: 25
    experiment: 'DDPM'
    output_dir: '/project/output_VAE'
    data_root: '/data/sleep-edfx/'
    run_dir: 'ldm_eeg'
    drop_last: false
    base_lr: 0.0001
    save_every: 50

ddpm:
  params:
    timesteps: 1000
    beta_schedule: "linear"
    linear_start: 0.0015
    linear_end: 0.0195
    loss_type: "l2"
    log_every_t: 200
    clip_denoised: False
    original_elbo_weight: 0.0
    v_posterior: 0.0
    l_simple_weight: 1.0
    parameterization: "eps"
    learn_logvar: False
    logvar_init: 0.0
    unet_config:
      params:
        image_size: 200
        in_channels: 8
        out_channels: 8
        model_channels: 64
        attention_resolutions: [25,8]
        num_res_blocks: 2
        channel_mult: [1,2,4]
        dropout: 0.1
        conv_resample: True
        num_heads: 1
        use_scale_shift_norm: True
        resblock_updown: True